title: shahriar.github.io # your name (or website title) here
logo: "/images/my_photo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Student in Biological & Environmental Sciences
  Department of Geosciences, University of Rhode Island
  <a href="https://www.linkedin.com/in/shahriar-b-shahid/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
