title: shahriar247.github.io # your name (or website title) here
logo: "/images/my_photo.jpg?raw=true" # your photo (or logo) here
<br>
description: > # your text below (remove <br> elements if you don't need line breaks)
<br>
  Graduate Student in Biological & Environmental Sciences
<br>
  Department of Geosciences, University of Rhode Island
  <a href="https://www.linkedin.com/in/shahriar-b-shahid/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
